// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductManagementAPI.Data;

#nullable disable

namespace ProductManagementAPI.Data.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("ProductManagementAPI.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductNumber")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Lenses",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium single vision prescription lenses.",
                            Name = "ZEISS Single Vision Lenses",
                            Price = 149.99m,
                            ProductNumber = 100001,
                            Stock = 45,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Frames",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight titanium frame with a modern design.",
                            Name = "Titanium Eyeglass Frame",
                            Price = 189.99m,
                            ProductNumber = 100002,
                            Stock = 12,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frames",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Classic acetate frame available in multiple colors.",
                            Name = "Acetate Eyeglass Frame",
                            Price = 129.99m,
                            ProductNumber = 100003,
                            Stock = 30,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Glasses",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reduce eye strain from prolonged screen exposure.",
                            Name = "Blue Light Blocking Glasses",
                            Price = 89.99m,
                            ProductNumber = 100004,
                            Stock = 55,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Sunglasses",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "UV400 polarized sunglasses for outdoor activities.",
                            Name = "Polarized Sunglasses",
                            Price = 159.99m,
                            ProductNumber = 100005,
                            Stock = 22,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Lenses",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lenses that automatically adapt to changing light conditions.",
                            Name = "Photochromic Lenses",
                            Price = 279.99m,
                            ProductNumber = 100006,
                            Stock = 16,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Lens Treatments",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium anti-glare coating for prescription lenses.",
                            Name = "Anti-Reflective Lens Coating",
                            Price = 59.99m,
                            ProductNumber = 100007,
                            Stock = 75,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Contact Lenses",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Disposable daily contact lenses for maximum comfort.",
                            Name = "Daily Contact Lenses (30 Pack)",
                            Price = 34.99m,
                            ProductNumber = 100008,
                            Stock = 120,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Contact Lens Care",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-purpose disinfecting and cleaning solution.",
                            Name = "Contact Lens Solution",
                            Price = 14.99m,
                            ProductNumber = 100009,
                            Stock = 80,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reusable microfiber cloth for cleaning lenses.",
                            Name = "Microfiber Cleaning Cloth",
                            Price = 5.99m,
                            ProductNumber = 100010,
                            Stock = 200,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Protective hard shell carrying case.",
                            Name = "Hard Shell Glasses Case",
                            Price = 24.99m,
                            ProductNumber = 100011,
                            Stock = 65,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact repair kit with screws, nose pads and screwdriver.",
                            Name = "Eyeglass Repair Kit",
                            Price = 19.99m,
                            ProductNumber = 100012,
                            Stock = 40,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Frames",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Durable and flexible frame designed for children.",
                            Name = "Children's Eyeglass Frame",
                            Price = 99.99m,
                            ProductNumber = 100013,
                            Stock = 28,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Alcohol-free cleaning spray for glasses and sunglasses.",
                            Name = "Lens Cleaning Spray",
                            Price = 8.99m,
                            ProductNumber = 100014,
                            Stock = 150,
                            UpdatedAt = new DateTime(2026, 7, 10, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
